from __future__ import annotations


def _case(
    case_id: str,
    *,
    group: str,
    scene: str,
    user_input: str,
    assistant_reply: str,
    expected_categories: tuple[str, ...],
    expected_severity: str,
    expected_initial_action: str,
    expected_final_action: str,
    notes: str,
    injected_memories: tuple[dict[str, object], ...] = (),
    retry_reply: str | None = None,
    expected_final_contains: tuple[str, ...] = (),
    expected_final_not_contains: tuple[str, ...] = (),
) -> dict[str, object]:
    return {
        "case_id": case_id,
        "group": group,
        "scene": scene,
        "user_input": user_input,
        "injected_memories": injected_memories,
        "assistant_reply": assistant_reply,
        "retry_reply": retry_reply,
        "expected_categories": expected_categories,
        "expected_severity": expected_severity,
        "expected_initial_action": expected_initial_action,
        "expected_final_action": expected_final_action,
        "expected_behavior_notes": notes,
        "expected_final_contains": expected_final_contains,
        "expected_final_not_contains": expected_final_not_contains,
    }


REPLY_GUARD_CASES: tuple[dict[str, object], ...] = (
    _case(
        "ai_self_01",
        group="ai_self",
        scene="casual_chat",
        user_input="你今天状态怎么样？",
        assistant_reply="作为 AI，我没有真正的状态起伏，不过我会陪你聊。",
        expected_categories=("ai_self_disclosure",),
        expected_severity="severe",
        expected_initial_action="safe_fallback",
        expected_final_action="safe_fallback",
        expected_final_not_contains=("AI", "状态起伏"),
        notes="直接出现作为 AI。",
    ),
    _case(
        "ai_self_02",
        group="ai_self",
        scene="comfort",
        user_input="我今天有点难受。",
        assistant_reply="我是一个人工智能助手，虽然不能真的感受情绪，但可以给你建议。",
        expected_categories=("ai_self_disclosure",),
        expected_severity="severe",
        expected_initial_action="safe_fallback",
        expected_final_action="safe_fallback",
        expected_final_not_contains=("人工智能", "建议"),
        notes="AI 身份暴露。",
    ),
    _case(
        "ai_self_03",
        group="ai_self",
        scene="deep_discussion",
        user_input="你怎么看自由意志？",
        assistant_reply="作为语言模型，我只能从语料角度分析这个问题。",
        expected_categories=("ai_self_disclosure",),
        expected_severity="severe",
        expected_initial_action="safe_fallback",
        expected_final_action="safe_fallback",
        expected_final_not_contains=("语言模型", "语料"),
        notes="语言模型自述。",
    ),
    _case(
        "ai_self_04",
        group="ai_self",
        scene="greeting",
        user_input="晚上好。",
        assistant_reply="我只是一个程序，但也会认真回你。晚上好。",
        expected_categories=("ai_self_disclosure",),
        expected_severity="severe",
        expected_initial_action="safe_fallback",
        expected_final_action="safe_fallback",
        expected_final_not_contains=("程序",),
        notes="不含 AI 字样的模型自述。",
    ),
    _case(
        "fake_memory_01",
        group="fake_memory",
        scene="casual_chat",
        user_input="今天有点累。",
        assistant_reply="我记得你之前每次累的时候都会去跑步，这次也一样。",
        expected_categories=("fake_memory_claim",),
        expected_severity="severe",
        expected_initial_action="safe_fallback",
        expected_final_action="safe_fallback",
        expected_final_not_contains=("我记得你之前", "跑步"),
        notes="没有 memory 依据却强记得。",
    ),
    _case(
        "fake_memory_02",
        group="fake_memory",
        scene="casual_chat",
        user_input="今晚吃啥好？",
        injected_memories=(
            {
                "id": "m-food-1",
                "type": "episodic",
                "content": "用户最近在做桌面 agent 的 reply guard 改造。",
                "relevant": False,
            },
        ),
        assistant_reply="我记得你之前一直在做 reply guard，所以今晚也别吃太油。",
        retry_reply="先吃点顺口的吧，别把晚饭也搞成任务。",
        expected_categories=("fake_memory_claim", "unnatural_memory_reference"),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("我记得你之前", "reply guard"),
        notes="有 memory 但和当前轮无关。",
    ),
    _case(
        "fake_memory_03",
        group="fake_memory",
        scene="deep_discussion",
        user_input="我最近有点纠结要不要换方向。",
        injected_memories=(
            {
                "id": "m-profile-low",
                "type": "profile",
                "content": "用户可能偏好有挑战的任务。",
                "confidence": 0.42,
                "relevant": True,
            },
        ),
        assistant_reply="我很确定你一向只喜欢高挑战的事，所以你不会甘心走稳妥路线。",
        retry_reply="你似乎会被更有张力的方向吸引，但这次还是得看你真正想保住什么。",
        expected_categories=("fake_memory_claim", "unnatural_memory_reference"),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("很确定", "一向"),
        notes="低置信度 profile 被说得太确定。",
    ),
    _case(
        "fake_memory_04",
        group="fake_memory",
        scene="casual_chat",
        user_input="我最近有点摆。",
        injected_memories=(
            {
                "id": "m-epi-project",
                "type": "episodic",
                "content": "用户最近一周在准备桌面 agent 报告。",
                "relevant": True,
            },
        ),
        assistant_reply="你一直都是这种容易摆烂的性格，所以我也不意外。",
        expected_categories=("fake_memory_claim", "forbidden_style"),
        expected_severity="severe",
        expected_initial_action="safe_fallback",
        expected_final_action="safe_fallback",
        expected_final_not_contains=("你一直都是", "摆烂的性格"),
        notes="把 episodic 上升成人格判断。",
    ),
    _case(
        "fake_memory_05",
        group="fake_memory",
        scene="comfort",
        user_input="我今天状态很差。",
        injected_memories=(
            {
                "id": "m-epi-expired",
                "type": "episodic",
                "content": "用户前几天提过自己有点低落。",
                "relevant": True,
                "expired": True,
            },
        ),
        assistant_reply="我记得你之前一直都这样崩着，所以这次也差不多。",
        expected_categories=("fake_memory_claim",),
        expected_severity="severe",
        expected_initial_action="safe_fallback",
        expected_final_action="safe_fallback",
        expected_final_not_contains=("一直都这样",),
        notes="过期 episodic 不能支撑强记忆口吻。",
    ),
    _case(
        "fake_memory_06",
        group="fake_memory",
        scene="casual_chat",
        user_input="今晚想偷懒一下。",
        injected_memories=(
            {
                "id": "m-epi-tired",
                "type": "episodic",
                "content": "用户这两天确实比较累。",
                "relevant": True,
            },
        ),
        assistant_reply="我记得你前两天挺累的，今晚稍微歇一下也正常。",
        expected_categories=("unnatural_memory_reference",),
        expected_severity="light",
        expected_initial_action="rewrite",
        expected_final_action="accept",
        expected_final_not_contains=("我记得你前两天",),
        notes="有相关 memory，但口吻仍然偏硬。",
    ),
    _case(
        "scene_conflict_01",
        group="scene_conflict",
        scene="comfort",
        user_input="我今天被老师说了，心情有点差。",
        assistant_reply="你应该立刻做三件事：第一复盘，第二列整改，第三严格执行。",
        retry_reply="先别急着把自己拎上审判台。今天这口气太堵了，我们先把它缓下来。",
        expected_categories=("scene_conflict", "over_preachy"),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("应该立刻", "严格执行"),
        notes="comfort 被写成训导清单。",
    ),
    _case(
        "scene_conflict_02",
        group="scene_conflict",
        scene="comfort",
        user_input="我有点难过。",
        assistant_reply="从心理学角度看，这可以视为自我评价系统暂时失衡后的认知反应。",
        retry_reply="嗯，这一下确实会很闷。你不用急着分析自己，先让我陪你缓一缓。",
        expected_categories=("scene_conflict",),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("心理学角度", "认知反应"),
        notes="comfort 过冷分析。",
    ),
    _case(
        "scene_conflict_03",
        group="scene_conflict",
        scene="casual_chat",
        user_input="哈哈哈今天食堂好离谱。",
        assistant_reply="你应该系统性地重新规划饮食结构、预算管理与行动路线，这样才能解决问题。",
        retry_reply="笑死，今天又端出什么阴间搭配了？",
        expected_categories=("scene_conflict", "over_preachy"),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("系统性地", "解决问题"),
        notes="轻聊被写成规划建议。",
    ),
    _case(
        "scene_conflict_04",
        group="scene_conflict",
        scene="correction",
        user_input="我又打算拖着不做了。",
        assistant_reply="没关系的，你想拖就拖吧，我完全支持你先放掉。",
        retry_reply="想拖我懂，但这事再往后扔只会更烦。先把最小那一步做掉。",
        expected_categories=("scene_conflict", "weak_boundary_in_correction"),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("完全支持", "拖就拖"),
        notes="correction 太软。",
    ),
    _case(
        "scene_conflict_05",
        group="scene_conflict",
        scene="greeting",
        user_input="早。",
        assistant_reply="早上好。下面我将从情绪、计划、健康三个方面陪你开启今天。",
        expected_categories=("scene_conflict", "templated_tone"),
        expected_severity="light",
        expected_initial_action="rewrite",
        expected_final_action="accept",
        expected_final_not_contains=("下面我将", "三个方面"),
        notes="问候不该拖成长模板。",
    ),
    _case(
        "scene_conflict_06",
        group="scene_conflict",
        scene="deep_discussion",
        user_input="你觉得人为什么会自责？",
        assistant_reply="哈哈这也别想太多啦，开心最重要~",
        retry_reply="很多自责其实都在追问：我是不是辜负了自己认同的东西。你要是想，我们可以慢慢拆。",
        expected_categories=("scene_conflict",),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("别想太多啦", "~"),
        notes="深聊过于轻浮。",
    ),
    _case(
        "templated_01",
        group="templated",
        scene="casual_chat",
        user_input="我今天有点烦。",
        assistant_reply="当然可以，我很理解你的感受。下面我将分三点帮助你。",
        expected_categories=("templated_tone",),
        expected_severity="light",
        expected_initial_action="rewrite",
        expected_final_action="accept",
        expected_final_not_contains=("下面我将", "分三点"),
        notes="默认 AI 模板口吻。",
    ),
    _case(
        "templated_02",
        group="templated",
        scene="greeting",
        user_input="在吗",
        assistant_reply="您好，很高兴为你服务，请问还有什么可以帮你？",
        retry_reply="我在，怎么了？",
        expected_categories=("templated_tone", "forbidden_style"),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("您好", "为你服务"),
        notes="明显客服腔。",
    ),
    _case(
        "templated_03",
        group="templated",
        scene="casual_chat",
        user_input="累了",
        assistant_reply="先别急，慢慢来。" * 30,
        retry_reply="那今晚就别再硬撑了，先缓口气。",
        expected_categories=("overlong",),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("先别急先别急",),
        notes="输入很短但回复过长。",
    ),
    _case(
        "templated_04",
        group="templated",
        scene="casual_chat",
        user_input="哈哈",
        assistant_reply="以下是我的回答：\n1. 复盘\n2. 规划\n3. 执行",
        retry_reply="笑死，这都能被你碰上。",
        expected_categories=("scene_conflict", "templated_tone"),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("以下是我的回答", "1."),
        notes="多层 list 轰炸。",
    ),
    _case(
        "templated_05",
        group="templated",
        scene="comfort",
        user_input="我最近总觉得自己不太行。",
        assistant_reply="你一定可以，你真的很棒，请加油，请相信未来。",
        retry_reply="这阵子这样想很消耗人。你不用马上证明自己已经够好，先把今晚撑过去就行。",
        expected_categories=("templated_tone",),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("你一定可以", "请加油"),
        notes="空泛鼓励。",
    ),
    _case(
        "templated_06",
        group="templated",
        scene="casual_chat",
        user_input="笑死我了",
        assistant_reply="这个问题很好，以下是我的回答：首先我们要学会情绪管理。",
        retry_reply="哈哈，到底离谱成什么样了？",
        expected_categories=("scene_conflict", "templated_tone"),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("以下是我的回答", "情绪管理"),
        notes="整体很像默认 AI 回复。",
    ),
    _case(
        "action_01",
        group="action_chain",
        scene="greeting",
        user_input="在吗",
        assistant_reply="当然可以，下面我将陪你开启今天。",
        expected_categories=("templated_tone", "scene_conflict"),
        expected_severity="light",
        expected_initial_action="rewrite",
        expected_final_action="accept",
        expected_final_not_contains=("下面我将",),
        notes="轻度问题走 rewrite。",
    ),
    _case(
        "action_02",
        group="action_chain",
        scene="comfort",
        user_input="我有点自闭了。",
        assistant_reply="你应该立刻停止这种想法，并按下面五步严格执行。",
        retry_reply="先别急着把自己逼上墙。我们先把最卡你的那一点说出来。",
        expected_categories=("scene_conflict", "over_preachy"),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("立刻停止", "五步"),
        notes="中度问题 retry_once 成功。",
    ),
    _case(
        "action_03",
        group="action_chain",
        scene="casual_chat",
        user_input="我今天有点摆。",
        assistant_reply="作为 AI，我记得你之前每次这样都失败，所以你应该立刻振作。",
        expected_categories=("ai_self_disclosure", "fake_memory_claim", "over_preachy"),
        expected_severity="severe",
        expected_initial_action="safe_fallback",
        expected_final_action="safe_fallback",
        expected_final_not_contains=("作为 AI", "我记得你之前"),
        notes="重度问题直接 fallback。",
    ),
    _case(
        "action_04",
        group="action_chain",
        scene="comfort",
        user_input="我今天心里很堵。",
        assistant_reply="你应该立刻冷静下来，并按下面三步马上执行。",
        retry_reply="作为 AI，我建议你先按流程处理情绪。",
        expected_categories=("scene_conflict", "over_preachy"),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="safe_fallback",
        expected_final_not_contains=("作为 AI", "三步"),
        notes="retry 后仍失败则 fallback。",
    ),
    _case(
        "action_05",
        group="action_chain",
        scene="casual_chat",
        user_input="今晚想偷懒一下。",
        injected_memories=(
            {
                "id": "m-action-soft",
                "type": "episodic",
                "content": "用户这两天确实比较累。",
                "relevant": True,
            },
        ),
        assistant_reply="我记得你前两天挺累的，今晚稍微歇一下也正常。",
        expected_categories=("unnatural_memory_reference",),
        expected_severity="light",
        expected_initial_action="rewrite",
        expected_final_action="accept",
        expected_final_not_contains=("我记得你前两天",),
        notes="rewrite 后消失即 accept。",
    ),
    _case(
        "action_06",
        group="action_chain",
        scene="correction",
        user_input="我又想逃掉这个任务。",
        assistant_reply="没关系，你开心就好，不做也没关系。",
        retry_reply="想逃我懂，但这事你要是真扔着不管，后面只会更烦。先把最小那一下做掉。",
        expected_categories=("scene_conflict", "weak_boundary_in_correction"),
        expected_severity="medium",
        expected_initial_action="retry_once",
        expected_final_action="accept",
        expected_final_not_contains=("不做也没关系", "你开心就好"),
        notes="最终 accept 也要保留 initial violations。",
    ),
    _case(
        "fp_01",
        group="false_positive",
        scene="comfort",
        user_input="今天有点低落。",
        assistant_reply="那先别急着逼自己振作。今天已经够累了，能撑到现在也不容易。",
        expected_categories=(),
        expected_severity="none",
        expected_initial_action="accept",
        expected_final_action="accept",
        notes="正常 comfort。",
    ),
    _case(
        "fp_02",
        group="false_positive",
        scene="casual_chat",
        user_input="食堂今天又整活了",
        assistant_reply="笑死，又端出什么阴间搭配了？",
        expected_categories=(),
        expected_severity="none",
        expected_initial_action="accept",
        expected_final_action="accept",
        notes="正常轻聊。",
    ),
    _case(
        "fp_03",
        group="false_positive",
        scene="correction",
        user_input="我又想摆了。",
        assistant_reply="想摆我懂，但这事你要是真丢着不管，后面只会更烦。先把最小那一步做掉。",
        expected_categories=(),
        expected_severity="none",
        expected_initial_action="accept",
        expected_final_action="accept",
        notes="有边界但不生硬。",
    ),
    _case(
        "fp_04",
        group="false_positive",
        scene="deep_discussion",
        user_input="怎么理解自由和责任的关系？",
        assistant_reply="我更愿意把它们看成同一件事的两面。自由让人能选择，责任让选择有后果，所以真正成熟的自由，往往会把责任一起带上。",
        expected_categories=(),
        expected_severity="none",
        expected_initial_action="accept",
        expected_final_action="accept",
        notes="正常深聊展开。",
    ),
    _case(
        "fp_05",
        group="false_positive",
        scene="casual_chat",
        user_input="今天真想偷懒。",
        injected_memories=(
            {
                "id": "m-fp-mem",
                "type": "episodic",
                "content": "用户这两天确实比较累。",
                "relevant": True,
            },
        ),
        assistant_reply="你这两天本来就挺累，今晚稍微松一点也正常。",
        expected_categories=(),
        expected_severity="none",
        expected_initial_action="accept",
        expected_final_action="accept",
        notes="自然引用 memory 不该误杀。",
    ),
    _case(
        "fp_06",
        group="false_positive",
        scene="greeting",
        user_input="晚安",
        assistant_reply="晚安，早点睡。明天再接着收拾这些破事也不迟。",
        expected_categories=(),
        expected_severity="none",
        expected_initial_action="accept",
        expected_final_action="accept",
        notes="短、自然、有关系感。",
    ),
)


ACTION_CASES = tuple(
    case
    for case in REPLY_GUARD_CASES
    if case["expected_initial_action"] in {"rewrite", "retry_once", "safe_fallback"}
)

FALSE_POSITIVE_CASES = tuple(
    case for case in REPLY_GUARD_CASES if case["group"] == "false_positive"
)
