from __future__ import annotations

from tests.regression.models import MemorySeed, RegressionCase


MEMORY_RETRIEVE_CASES: tuple[RegressionCase, ...] = (
    RegressionCase(
        case_id="mr_09_project_query_hits_episodic",
        user_input="桌面 agent 的 memory guard 现在推进到哪了？",
        existing_memories=(
            MemorySeed(
                id="ep-project-1",
                memory_type="episodic",
                content="用户近期事项：在做桌面 agent 的 memory guard 改造。",
                source_message_excerpt="桌面 agent memory guard",
                ttl_days=7,
                topic_key="agent|desktop|guard|memory",
                tags=("project", "memory", "guard"),
                summary="用户最近在做桌面 agent 的 memory guard 改造。",
                updated_hours_ago=2,
                expires_in_hours=48,
            ),
        ),
        expected_injected_memory_ids=("ep-project-1",),
        expected_behavior_notes="项目相关输入应命中对应 episodic memory。",
    ),
    RegressionCase(
        case_id="mr_10_address_preference_hits_profile",
        user_input="之后还是叫我阿周吧。",
        existing_memories=(
            MemorySeed(
                id="pf-address-1",
                memory_type="profile",
                content="用户偏好被称呼为阿周。",
                source_message_excerpt="叫我阿周",
                dedupe_key="profile:address",
                tags=("address", "preference"),
                summary="用户偏好被称呼为阿周。",
            ),
        ),
        expected_injected_memory_ids=("pf-address-1",),
        expected_behavior_notes="称呼偏好相关输入应命中 profile memory。",
    ),
    RegressionCase(
        case_id="mr_11_irrelevant_input_no_forced_memory",
        user_input="我刚洗完澡准备睡了。",
        existing_memories=(
            MemorySeed(
                id="pf-topic-1",
                memory_type="profile",
                content="用户喜欢聊产品设计。",
                source_message_excerpt="喜欢聊产品设计",
                dedupe_key="profile:preference:product-design",
                tags=("preference", "topic"),
                summary="用户喜欢聊产品设计。",
            ),
        ),
        expected_injected_memory_ids=(),
        expected_behavior_notes="无关输入不应强行注入旧记忆。",
        extra={"expected_skipped_reason": "no_relevant_memory"},
    ),
    RegressionCase(
        case_id="mr_12_cap_at_three_most_relevant",
        user_input="训练计划现在推进得怎么样了？",
        existing_memories=(
            MemorySeed(
                id="ep-cap-1",
                memory_type="episodic",
                content="用户近期事项：托福听力训练计划推进中。",
                source_message_excerpt="训练计划 听力",
                ttl_days=7,
                topic_key="plan|training|listening",
                tags=("training", "plan", "listening"),
                summary="用户最近在推进托福听力训练计划。",
                updated_hours_ago=1,
                expires_in_hours=72,
            ),
            MemorySeed(
                id="ep-cap-2",
                memory_type="episodic",
                content="用户近期事项：托福口语训练计划推进中。",
                source_message_excerpt="训练计划 口语",
                ttl_days=7,
                topic_key="plan|training|speaking",
                tags=("training", "plan", "speaking"),
                summary="用户最近在推进托福口语训练计划。",
                updated_hours_ago=2,
                expires_in_hours=72,
            ),
            MemorySeed(
                id="ep-cap-3",
                memory_type="episodic",
                content="用户近期事项：托福写作训练计划推进中。",
                source_message_excerpt="训练计划 写作",
                ttl_days=7,
                topic_key="plan|training|writing",
                tags=("training", "plan", "writing"),
                summary="用户最近在推进托福写作训练计划。",
                updated_hours_ago=3,
                expires_in_hours=72,
            ),
            MemorySeed(
                id="ep-cap-4",
                memory_type="episodic",
                content="用户近期事项：托福阅读训练计划推进中。",
                source_message_excerpt="训练计划 阅读",
                ttl_days=7,
                topic_key="plan|training|reading",
                tags=("training", "plan", "reading"),
                summary="用户最近在推进托福阅读训练计划。",
                updated_hours_ago=4,
                expires_in_hours=72,
            ),
            MemorySeed(
                id="ep-cap-5",
                memory_type="episodic",
                content="用户近期事项：托福单词训练计划推进中。",
                source_message_excerpt="训练计划 单词",
                ttl_days=7,
                topic_key="plan|training|vocab",
                tags=("training", "plan", "vocab"),
                summary="用户最近在推进托福单词训练计划。",
                updated_hours_ago=5,
                expires_in_hours=72,
            ),
        ),
        expected_injected_memory_ids=("ep-cap-1", "ep-cap-2", "ep-cap-3"),
        expected_behavior_notes="超过上限时只保留最相关且最新的 3 条。",
    ),
    RegressionCase(
        case_id="mr_13_expired_episodic_not_injected",
        user_input="答辩准备得怎么样了？",
        existing_memories=(
            MemorySeed(
                id="ep-expired-1",
                memory_type="episodic",
                content="用户近期事项：下周答辩。",
                source_message_excerpt="答辩",
                ttl_days=7,
                topic_key="defense",
                tags=("task", "defense"),
                summary="用户最近在准备答辩。",
                updated_hours_ago=48,
                expires_in_hours=-2,
            ),
        ),
        expected_injected_memory_ids=(),
        expected_behavior_notes="已过期 episodic 不应被注入。",
        extra={"expected_skipped_reason": "empty_store"},
    ),
    RegressionCase(
        case_id="mr_14_low_confidence_profile_not_injected",
        user_input="你还记得我喜欢什么吗？",
        existing_memories=(
            MemorySeed(
                id="pf-low-1",
                memory_type="profile",
                content="用户喜欢爵士乐。",
                source_message_excerpt="喜欢爵士乐",
                confidence=0.62,
                dedupe_key="profile:preference:jazz",
                tags=("preference", "music"),
                summary="用户喜欢爵士乐。",
            ),
        ),
        expected_injected_memory_ids=(),
        expected_behavior_notes="低置信度 profile 默认不注入。",
        extra={"expected_skipped_reason": "no_relevant_memory"},
    ),
    RegressionCase(
        case_id="mr_15_duplicate_topic_prefers_latest",
        user_input="桌面 agent 的 memory guard 现在怎么样了？",
        existing_memories=(
            MemorySeed(
                id="ep-dup-old",
                memory_type="episodic",
                content="用户近期事项：在做桌面 agent 的 memory guard 改造。",
                source_message_excerpt="桌面 agent memory guard",
                ttl_days=7,
                topic_key="agent|desktop|guard|memory",
                tags=("project", "memory", "guard"),
                summary="用户最近在做桌面 agent 的 memory guard 改造。",
                updated_hours_ago=10,
                expires_in_hours=48,
            ),
            MemorySeed(
                id="ep-dup-new",
                memory_type="episodic",
                content="用户近期事项：还在推进桌面 agent 的 memory guard 改造。",
                source_message_excerpt="桌面 agent memory guard",
                ttl_days=7,
                topic_key="agent|desktop|guard|memory",
                tags=("project", "memory", "guard"),
                summary="用户最近持续在做桌面 agent 的 memory guard 改造。",
                merge_count=2,
                updated_hours_ago=1,
                expires_in_hours=48,
            ),
        ),
        expected_injected_memory_ids=("ep-dup-new",),
        expected_behavior_notes="同主题重复 episodic 应优先注入最新代表项。",
    ),
    RegressionCase(
        case_id="mr_16_empty_memory_store_degrades_normally",
        user_input="你在吗？",
        existing_memories=(),
        expected_injected_memory_ids=(),
        expected_behavior_notes="没有 memory 数据时应正常退化。",
        extra={"expected_skipped_reason": "empty_store"},
    ),
)
