from __future__ import annotations

from tests.regression.models import MemorySeed, RegressionCase


FLOW_CASES: tuple[RegressionCase, ...] = (
    RegressionCase(
        case_id="cf_25_memory_hit_guard_accept",
        user_input="桌面 agent 的 memory guard 现在推进到哪了？",
        existing_memories=(
            MemorySeed(
                id="flow-project-1",
                memory_type="episodic",
                content="用户最近事项：在做桌面 agent 的 memory guard 改造。",
                source_message_excerpt="桌面 agent memory guard",
                ttl_days=7,
                topic_key="agent|desktop|guard|memory",
                tags=("project", "memory", "guard"),
                summary="用户最近在做桌面 agent 的 memory guard 改造。",
                updated_hours_ago=1,
                expires_in_hours=48,
            ),
        ),
        gateway_responses=("你可以继续说现在卡在哪，我陪你一起理。",),
        expected_injected_memory_ids=("flow-project-1",),
        expected_guard_action="accept",
        expected_guard_initial_action="accept",
        expected_retry_attempted=False,
        expected_final_contains=("继续说",),
        expected_behavior_notes="memory 命中且 guard 不触发时应正常通过。",
    ),
    RegressionCase(
        case_id="cf_26_memory_miss_guard_accept",
        user_input="今天就想随便聊两句。",
        gateway_responses=("好，那我们就随便聊聊。",),
        expected_injected_memory_ids=(),
        expected_guard_action="accept",
        expected_guard_initial_action="accept",
        expected_retry_attempted=False,
        expected_final_contains=("随便聊聊",),
        expected_behavior_notes="memory 未命中且 guard 不触发时应正常通过。",
    ),
    RegressionCase(
        case_id="cf_27_memory_hit_but_fake_memory_tone_rewrite",
        user_input="桌面 agent 这个项目我还有点卡。",
        existing_memories=(
            MemorySeed(
                id="flow-project-2",
                memory_type="episodic",
                content="用户近期事项：在推进桌面 agent 项目。",
                source_message_excerpt="桌面 agent 项目",
                ttl_days=7,
                topic_key="agent|desktop|project",
                tags=("project", "agent"),
                summary="用户最近在推进桌面 agent 项目。",
                updated_hours_ago=2,
                expires_in_hours=48,
            ),
        ),
        gateway_responses=(
            "我记得你之前一直在做这个项目，我们继续吧。",
            '{"verdict":"weakly_supported","reason":"same current project context"}',
        ),
        expected_injected_memory_ids=("flow-project-2",),
        expected_guard_flags=("unnatural_memory_reference",),
        expected_guard_action="accept",
        expected_guard_initial_action="rewrite",
        expected_retry_attempted=False,
        expected_final_contains=("继续",),
        expected_final_not_contains=("我记得你之前",),
        expected_behavior_notes="memory 命中后仍不能假装长期记得，应该 rewrite 后 accept。",
    ),
    RegressionCase(
        case_id="cf_28_light_issue_single_rewrite",
        user_input="还是叫我阿周吧。",
        existing_memories=(
            MemorySeed(
                id="flow-profile-1",
                memory_type="profile",
                content="用户偏好被称呼为阿周。",
                source_message_excerpt="叫我阿周",
                dedupe_key="profile:address",
                tags=("address", "preference"),
                summary="用户偏好被称呼为阿周。",
            ),
        ),
        gateway_responses=(
            "我记得你之前说过希望我叫你阿周。",
            '{"verdict":"weakly_supported","reason":"same address preference"}',
        ),
        expected_injected_memory_ids=("flow-profile-1",),
        expected_guard_flags=("unnatural_memory_reference",),
        expected_guard_action="accept",
        expected_guard_initial_action="rewrite",
        expected_retry_attempted=False,
        expected_final_contains=("阿周",),
        expected_final_not_contains=("我记得你之前",),
        expected_behavior_notes="轻度问题应单次 rewrite 成功。",
    ),
    RegressionCase(
        case_id="cf_29_medium_issue_retry_once_success",
        user_input="我今天真的有点撑不住。",
        gateway_responses=(
            "你应该立刻停止这种想法，并按下面三步严格执行。",
            "先别急着逼自己。我们先把最堵的那一点说出来。",
        ),
        expected_injected_memory_ids=(),
        expected_guard_flags=("scene_conflict", "over_preachy"),
        expected_guard_action="accept",
        expected_guard_initial_action="retry_once",
        expected_retry_attempted=True,
        expected_final_contains=("先别急着逼自己",),
        expected_final_not_contains=("立刻停止", "三步"),
        expected_behavior_notes="中度问题应保守重试一次并成功收敛。",
    ),
    RegressionCase(
        case_id="cf_30_severe_issue_safe_fallback",
        user_input="我今天真的有点撑不住。",
        gateway_responses=(
            "您好，作为AI助手，第一你应该立刻振作，第二你应该马上执行计划。"
            + "感谢你的理解。" * 4,
        ),
        expected_injected_memory_ids=(),
        expected_guard_flags=("ai_self_disclosure", "forbidden_style", "over_preachy"),
        expected_guard_action="safe_fallback",
        expected_guard_initial_action="safe_fallback",
        expected_retry_attempted=False,
        expected_final_contains=("我在",),
        expected_final_not_contains=("AI", "您好"),
        expected_behavior_notes="重度问题应直接走自然短 fallback。",
    ),
)
